# FROM apache/superset:3.1.0
FROM apache/superset:3.0.0

# Switch to root to change file permissions
USER root

# Ensure the app directory exists and is owned by superset
RUN mkdir -p /app && chown -R superset /app
RUN chown superset:superset /app

# # Switch back to superset user
# USER superset 
# COPY ./custom_security_new.py /app/superset/security/security.py 
# COPY ./security_append.py /app/security_append.py 

COPY ./favicon.png /app/favicon.png
COPY ./superset_config.py /app

RUN chown superset:superset /app/superset_config.py
RUN chown superset:superset /app/favicon.png


USER superset
ENV LOGO_TARGET_PATH=/app/favicon.png
ENV SUPERSET_CONFIG_PATH=/app/superset_config.py
ENV SECRET_KEY=76598540-83c3-4b74-a9bb-4571535a526c 
ENV SUPERSET_SECRET_KEY=76598540-83c3-4b74-a9bb-4571535a526c

# ENV SUPERSET_WEBSERVER_TIMEOUT=800
# ENV SUPERSET_TIMEOUT=800


# RUN cat /app/security_append.py >> /app/superset/config.py 
# RUN grep -vwE "CUSTOM_SECURITY_MANAGER" /app/superset/config.py > /app/superset/config_fixed.py 
# RUN cat /app/security_append.py | cat - /app/superset/config_fixed.py > /app/superset/temp && mv /app/superset/temp /app/superset/config.py 
# # RUN sed -i 's/\"GENERIC_CHART_AXES\": False,/\"GENERIC_CHART_AXES\": True,/g' /app/superset/config.py
# # RUN sed -i 's/\"ENABLE_TEMPLATE_PROCESSING\": False,/\"ENABLE_TEMPLATE_PROCESSING\": True,/g' /app/superset/config.py
