APP_NAME: "ecosystem.Ai"

SUPERSET_TIMEOUT: 10000
SQLLAB_TIMEOUT: 2000
GUNICONR_TIMEOUT: 2000
SUPERSET_WEBSERVER_TIMEOUT: 2000
SQLLAB_ASYNC_TIME_LIMIT_SEC: 2000
SHOW_STACKTRACE: True

LOG_LEVEL: 'DEBUG'
TALISMAN_ENABLED = False